"use client"

import * as React from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import type { Good, MarketPrice } from "@/lib/admin-api"

export function AdminMarketControls({prices,goods,save}:{prices:MarketPrice[];goods:Good[];save:(p:string,b:unknown,m?:string)=>Promise<void>}) { const [price,setPrice]=React.useState({goodCode:"",goodName:"",unit:"kg",governmentPrice:"",marketPrice:"",previousMarketPrice:"",region:"National",marketName:"Government Reference Market"}); const [good,setGood]=React.useState({code:"",name:"",categoryCode:"vegetable",defaultUnit:"kg"}); return <div className="space-y-4"><div className="grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle>Set market price</CardTitle></CardHeader><CardContent><form className="grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();void save("/admin/prices",{...price,governmentPrice:+price.governmentPrice,marketPrice:+price.marketPrice,previousMarketPrice:+price.previousMarketPrice},"POST")}}>{Object.entries(price).map(([k,v])=><div key={k}><Label className="mb-1 capitalize">{k.replace(/([A-Z])/g," $1")}</Label><Input type={k.includes("Price")?"number":"text"} value={v} onChange={e=>setPrice(x=>({...x,[k]:e.target.value}))} required/></div>)}<Button className="sm:col-span-2">Save price</Button></form></CardContent></Card><Card><CardHeader><CardTitle>Add or update good</CardTitle></CardHeader><CardContent><form className="grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();void save("/admin/goods",{...good,active:true},"POST")}}>{Object.entries(good).map(([k,v])=><div key={k}><Label className="mb-1 capitalize">{k.replace(/([A-Z])/g," $1")}</Label><Input value={v} onChange={e=>setGood(x=>({...x,[k]:e.target.value}))} required/></div>)}<Button className="sm:col-span-2">Save good</Button></form></CardContent></Card></div><div className="grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle>Price records</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Good</TableHead><TableHead>Region</TableHead><TableHead>Government</TableHead><TableHead>Market</TableHead></TableRow></TableHeader><TableBody>{prices.slice(0,30).map(x=><TableRow key={x._id}><TableCell>{x.goodName}</TableCell><TableCell>{x.region}</TableCell><TableCell>{money(x.governmentPrice)}</TableCell><TableCell>{money(x.marketPrice)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card><Card><CardHeader><CardTitle>Goods catalog</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Name</TableHead><TableHead>Category</TableHead><TableHead>Unit</TableHead></TableRow></TableHeader><TableBody>{goods.map(x=><TableRow key={x._id}><TableCell>{x.name}</TableCell><TableCell>{x.categoryCode}</TableCell><TableCell>{x.defaultUnit}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></div></div> }

function money(value:number){return new Intl.NumberFormat("en-BD",{style:"currency",currency:"BDT",maximumFractionDigits:0}).format(value||0)}
