"use client"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import type { AdminUser, Deal, InventoryItem, Listing } from "@/lib/admin-api"

type Change = (path:string, body:unknown, method?:string)=>Promise<void>

export function UsersPanel({items,change}:{items:AdminUser[];change:Change}) { return <Card><CardHeader><CardTitle>Users</CardTitle><CardDescription>Approve accounts and change platform roles.</CardDescription></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>User</TableHead><TableHead>Role</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{items.map(x=><TableRow key={x._id}><TableCell><div className="font-medium">{x.name}</div><div className="text-xs text-muted-foreground">{x.phoneNumber} · {x.email||"No email"}</div></TableCell><TableCell><Select value={x.role} onValueChange={v=>v&&void change(`/admin/users/${x._id}`,{role:v})}><SelectTrigger className="w-36"><SelectValue/></SelectTrigger><SelectContent>{["farmer","buyer","agent","medicineSeller","admin"].map(v=><SelectItem value={v} key={v}>{v}</SelectItem>)}</SelectContent></Select></TableCell><TableCell><Status value={x.verificationStatus}/></TableCell><TableCell><div className="flex justify-end gap-2"><Button size="sm" onClick={()=>void change(`/admin/users/${x._id}`,{verificationStatus:"approved"})}>Approve</Button><Button size="sm" variant="destructive" onClick={()=>void change(`/admin/users/${x._id}`,{verificationStatus:"rejected"})}>Reject</Button></div></TableCell></TableRow>)}</TableBody></Table></CardContent></Card> }

const statuses = ["draft", "pendingOtp", "published", "reserved", "sold", "expired", "cancelled", "rejected"]
export function ListingsPanel({items,change}:{items:Listing[];change:Change}) { return <Card><CardHeader><CardTitle>All listings</CardTitle><CardDescription>Review and control every marketplace listing.</CardDescription></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Good</TableHead><TableHead>Owner</TableHead><TableHead>Quantity</TableHead><TableHead>Price</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{items.map(x=><TableRow key={x._id}><TableCell><b>{x.goodName}</b><div className="text-xs text-muted-foreground">{x.address||x.goodCode}</div></TableCell><TableCell className="font-mono text-xs">{short(x.ownerId)}</TableCell><TableCell>{x.quantity} {x.unit}</TableCell><TableCell>{money(x.minimumPrice)}</TableCell><TableCell><Select value={x.status} onValueChange={v=>v&&void change(`/admin/listings/${x._id}`,{status:v})}><SelectTrigger className="w-36"><SelectValue/></SelectTrigger><SelectContent>{statuses.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></TableCell></TableRow>)}</TableBody></Table></CardContent></Card> }

export function DealsPanel({items,change}:{items:Deal[];change:Change}) { return <Card><CardHeader><CardTitle>Deals</CardTitle><CardDescription>Transaction value and fulfillment status.</CardDescription></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Deal</TableHead><TableHead>Parties</TableHead><TableHead>Quantity</TableHead><TableHead>Total</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{items.map(x=><TableRow key={x._id}><TableCell className="font-mono text-xs">{short(x._id)}</TableCell><TableCell>Buyer {short(x.buyerId)}<div className="text-xs text-muted-foreground">Farmer {short(x.farmerId)}</div></TableCell><TableCell>{x.quantity} × {money(x.unitPrice)}</TableCell><TableCell className="font-semibold">{money(x.totalPrice)}</TableCell><TableCell><Select value={x.status} onValueChange={v=>v&&void change(`/admin/deals/${x._id}`,{status:v})}><SelectTrigger className="w-32"><SelectValue/></SelectTrigger><SelectContent>{["confirmed","completed","cancelled","disputed"].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></TableCell></TableRow>)}</TableBody></Table></CardContent></Card> }

export function InventoryPanel({items,change}:{items:InventoryItem[];change:Change}) { return <Card><CardHeader><CardTitle>Seller inventory</CardTitle><CardDescription>Stock, prices and shop visibility.</CardDescription></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Shop</TableHead><TableHead>Product</TableHead><TableHead>Stock</TableHead><TableHead>Price</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader><TableBody>{items.map(x=><TableRow key={x._id}><TableCell><b>{x.shopName}</b><div className="text-xs text-muted-foreground">{x.address}</div></TableCell><TableCell>{x.medicineName}<div><Badge variant="outline">{x.type}</Badge></div></TableCell><TableCell>{x.stockQuantity} {x.unit}</TableCell><TableCell>{money(x.price)}</TableCell><TableCell className="text-right"><Button size="sm" variant={x.active?"outline":"default"} onClick={()=>void change(`/admin/inventory/${x._id}`,{active:!x.active})}>{x.active?"Disable":"Enable"}</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card> }

function Status({value}:{value:string}) { return <Badge variant={value==="approved"||value==="active"?"default":value==="rejected"?"destructive":"secondary"}>{value}</Badge> }
function money(value:number){return new Intl.NumberFormat("en-BD",{style:"currency",currency:"BDT",maximumFractionDigits:0}).format(value||0)}
function short(value:string){return value.length>12?`${value.slice(0,6)}…${value.slice(-4)}`:value}
