"use client"

import * as React from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { apiRequest, type ApiEnvelope } from "@/lib/admin-api"

type Notice = { _id:string; title:string; message:string; targetRole:string; status:string; publishAt?:string; expiresAt?:string; attachmentUrl?:string }
type Ad = { _id:string; title:string; description:string; targetRole:string; active:boolean; startsAt?:string; endsAt?:string }
type Ticket = { _id:string; subject:string; message:string; status:string; priority:string; adminNote?:string }

export function CommunicationsManagementPanel() {
  const [notices,setNotices]=React.useState<Notice[]>([]), [ads,setAds]=React.useState<Ad[]>([]), [tickets,setTickets]=React.useState<Ticket[]>([])
  const [message,setMessage]=React.useState("")
  const [notice,setNotice]=React.useState({title:"",message:"",targetRole:"all",status:"draft",publishAt:"",expiresAt:"",attachmentUrl:""})
  const [ad,setAd]=React.useState({title:"",description:"",targetRole:"all",startsAt:"",endsAt:"",imageUrl:"",destinationUrl:""})
  const load=React.useCallback(async()=>{ try { const [n,a,t]=await Promise.all([apiRequest<ApiEnvelope<Notice[]>>("/admin/notices"),apiRequest<ApiEnvelope<Ad[]>>("/admin/advertisements"),apiRequest<ApiEnvelope<Ticket[]>>("/admin/support/tickets")]); setNotices(n.data);setAds(a.data);setTickets(t.data) } catch(e){setMessage(e instanceof Error?e.message:"Load failed")}},[])
  React.useEffect(()=>{void load()},[load])
  async function send(path:string, method:string, body?:unknown){ try{await apiRequest(path,{method,body:body?JSON.stringify(body):undefined});setMessage("Saved successfully");await load()}catch(e){setMessage(e instanceof Error?e.message:"Save failed")}}
  async function createNotice(){ if(!notice.title.trim()||!notice.message.trim()){setMessage("Title and message are required");return} await send("/admin/guidance","POST",{type:"notice",title:notice.title,message:notice.message,targetRole:notice.targetRole,active:notice.status==="published"}); const latest=await apiRequest<ApiEnvelope<Notice[]>>("/admin/notices"); const item=latest.data[0]; if(item) await send(`/admin/notices/${item._id}`,"PATCH",{status:notice.status,publishAt:notice.publishAt?new Date(notice.publishAt).toISOString():null,expiresAt:notice.expiresAt?new Date(notice.expiresAt).toISOString():null,attachmentUrl:notice.attachmentUrl||null}); setNotice({title:"",message:"",targetRole:"all",status:"draft",publishAt:"",expiresAt:"",attachmentUrl:""}) }
  async function createAd(){if(!ad.title.trim()){setMessage("Advertisement title is required");return}await send("/admin/advertisements","POST",{...ad,startsAt:ad.startsAt?new Date(ad.startsAt).toISOString():undefined,endsAt:ad.endsAt?new Date(ad.endsAt).toISOString():undefined});setAd({title:"",description:"",targetRole:"all",startsAt:"",endsAt:"",imageUrl:"",destinationUrl:""})}
  return <div className="space-y-6">
    {message?<Card><CardContent className="py-3">{message}</CardContent></Card>:null}
    <Card><CardHeader><CardTitle>Notice / CMS composer</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2">
      <Input placeholder="Title" value={notice.title} onChange={e=>setNotice({...notice,title:e.target.value})}/><select className="h-9 rounded-md border bg-background px-3" value={notice.targetRole} onChange={e=>setNotice({...notice,targetRole:e.target.value})}><option value="all">All roles</option><option value="farmer">Farmer</option><option value="buyer">Buyer</option><option value="agent">Agent</option><option value="medicineSeller">Medicine seller</option></select>
      <Textarea className="md:col-span-2" placeholder="Message" value={notice.message} onChange={e=>setNotice({...notice,message:e.target.value})}/>
      <select className="h-9 rounded-md border bg-background px-3" value={notice.status} onChange={e=>setNotice({...notice,status:e.target.value})}><option value="draft">Draft</option><option value="scheduled">Scheduled</option><option value="published">Publish now</option></select><Input placeholder="Attachment URL" value={notice.attachmentUrl} onChange={e=>setNotice({...notice,attachmentUrl:e.target.value})}/>
      <Input type="datetime-local" value={notice.publishAt} onChange={e=>setNotice({...notice,publishAt:e.target.value})}/><Input type="datetime-local" value={notice.expiresAt} onChange={e=>setNotice({...notice,expiresAt:e.target.value})}/><Button onClick={()=>void createNotice()}>Save notice</Button>
    </CardContent></Card>
    <div className="grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle>Notices</CardTitle></CardHeader><CardContent className="space-y-3">{notices.map(n=><div key={n._id} className="rounded-lg border p-3"><div className="font-medium">{n.title}</div><div className="text-sm text-muted-foreground">{n.targetRole} · {n.status}</div><p className="mt-2 text-sm">{n.message}</p><div className="mt-3 flex gap-2"><Button size="sm" variant="outline" onClick={()=>void send(`/admin/notices/${n._id}`,"PATCH",{status:n.status==="published"?"draft":"published"})}>{n.status==="published"?"Unpublish":"Publish"}</Button><Button size="sm" variant="destructive" onClick={()=>void send(`/admin/notices/${n._id}`,"DELETE")}>Delete</Button></div></div>)}</CardContent></Card>
    <Card><CardHeader><CardTitle>Advertisement management</CardTitle></CardHeader><CardContent className="space-y-3"><Input placeholder="Campaign title" value={ad.title} onChange={e=>setAd({...ad,title:e.target.value})}/><Textarea placeholder="Description" value={ad.description} onChange={e=>setAd({...ad,description:e.target.value})}/><Input placeholder="Image URL" value={ad.imageUrl} onChange={e=>setAd({...ad,imageUrl:e.target.value})}/><Input placeholder="Destination URL" value={ad.destinationUrl} onChange={e=>setAd({...ad,destinationUrl:e.target.value})}/><div className="grid grid-cols-2 gap-2"><Input type="datetime-local" value={ad.startsAt} onChange={e=>setAd({...ad,startsAt:e.target.value})}/><Input type="datetime-local" value={ad.endsAt} onChange={e=>setAd({...ad,endsAt:e.target.value})}/></div><Button onClick={()=>void createAd()}>Create advertisement</Button>{ads.map(a=><div key={a._id} className="rounded-lg border p-3"><b>{a.title}</b><div className="text-sm">{a.active?"Active":"Paused"} · {a.targetRole}</div><div className="mt-2 flex gap-2"><Button size="sm" variant="outline" onClick={()=>void send(`/admin/advertisements/${a._id}`,"PATCH",{active:!a.active})}>{a.active?"Pause":"Activate"}</Button><Button size="sm" variant="destructive" onClick={()=>void send(`/admin/advertisements/${a._id}`,"DELETE")}>Delete</Button></div></div>)}</CardContent></Card></div>
    <Card><CardHeader><CardTitle>Support ticket queue</CardTitle></CardHeader><CardContent className="space-y-3">{tickets.map(t=><div key={t._id} className="grid gap-2 rounded-lg border p-3 md:grid-cols-[1fr_180px_180px]"><div><b>{t.subject}</b><p className="text-sm text-muted-foreground">{t.message}</p></div><select className="h-9 rounded-md border bg-background px-2" value={t.priority} onChange={e=>void send(`/admin/support/tickets/${t._id}`,"PATCH",{priority:e.target.value})}><option>low</option><option>normal</option><option>high</option><option>urgent</option></select><select className="h-9 rounded-md border bg-background px-2" value={t.status} onChange={e=>void send(`/admin/support/tickets/${t._id}`,"PATCH",{status:e.target.value})}><option value="open">Open</option><option value="in_progress">In progress</option><option value="waiting">Waiting</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select></div>)}</CardContent></Card>
  </div>
}


